### ISSUE TITLE
Lack of Connect Wallet button on mobile app

### ISSUE THREAD

**Issue by Vienio99** [astroport-fi/astroport-lbp-frontend#2]
**Describe the bug:**
No "Connect Wallet" button on mobile app

**To Reproduce:**
Go to lockdrop.astroport.fi
Select "Go to active phase"

**Desktop:**
Iphone 7
Browser Safari (tried also on Chrome)

**Comment by stefanionescu** [comment]
Same as [this](https://github.com/astroport-fi/astroport-lbp-frontend/issues/3#issuecomment-1009326433).
