### ISSUE TITLE
"Get Chrome" button still showing even though Chrome is used

### ISSUE THREAD

**Issue by Vienio99** [astroport-fi/astroport-lbp-frontend#3]
**Describe the bug:**
"Get Chrome" button is still visible even though Chrome browser is used

**To Reproduce:**
Go to lockdrop.astroport.fi

**Image**
![264348631_872659170065034_3891994798491413374_n](https://user-images.githubusercontent.com/73585288/146532967-e9332ae5-be2a-44c2-8045-37acdb57342e.jpg)

**Desktop:**
Iphone 7
Browser Chrome

**Comment by stefanionescu** [comment]
Thank you for pointing this out! The lockdrop UI was not optimized for mobile and we're aware of the issue. Given that lockdrop is already done, this issue may be more relevant for other teams that want to use the Astro Lockdrop UI for their own protocol bootstrapping.

Will close this issue for now.
